export const data: {
  id: number;
  cup: string;
  trackName: string;
  isPlayed: boolean;
  isDLC: boolean;
}[] = [
  {
    id: 1,
    cup: 'Mushroom Cup',
    trackName: 'Mario Kart Stadium',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 2,
    cup: 'Mushroom Cup',
    trackName: 'Water Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 3,
    cup: 'Mushroom Cup',
    trackName: 'Sweet Sweet Canyon',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 4,
    cup: 'Mushroom Cup',
    trackName: 'Thwomp Ruins',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 5,
    cup: 'Flower Cup',
    trackName: 'Mario Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 6,
    cup: 'Flower Cup',
    trackName: 'Toad Harbor',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 7,
    cup: 'Flower Cup',
    trackName: 'Twisted Mansion',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 8,
    cup: 'Flower Cup',
    trackName: 'Shy Guy Falls',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 9,
    cup: 'Star Cup',
    trackName: 'Sunshine Airport',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 10,
    cup: 'Star Cup',
    trackName: 'Dolphin Shoals',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 11,
    cup: 'Star Cup',
    trackName: 'Electrodrome',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 12,
    cup: 'Star Cup',
    trackName: 'Mount Wario',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 13,
    cup: 'Special Cup',
    trackName: 'Cloudtop Cruise',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 14,
    cup: 'Special Cup',
    trackName: 'Bone Dry Dunes',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 15,
    cup: 'Special Cup',
    trackName: 'Bowsers Castle',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 16,
    cup: 'Special Cup',
    trackName: 'Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 17,
    cup: 'Shell Cup',
    trackName: 'Wii Moo Moo Meadows',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 18,
    cup: 'Shell Cup',
    trackName: 'GBA Mario Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 19,
    cup: 'Shell Cup',
    trackName: 'DS Cheep Cheep Beach',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 20,
    cup: 'Shell Cup',
    trackName: 'N64 Toads Turnpike',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 21,
    cup: 'Banana Cup',
    trackName: 'GCN Dry Dry Desert',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 22,
    cup: 'Banana Cup',
    trackName: 'SNES Donut Plains 3',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 23,
    cup: 'Banana Cup',
    trackName: 'N64 Royal Raceway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 24,
    cup: 'Banana Cup',
    trackName: '3DS DK Jungle',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 25,
    cup: 'Lightning Cup',
    trackName: 'DS Tick Tock Clock',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 26,
    cup: 'Lightning Cup',
    trackName: '3DS Piranha Plant Slide',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 27,
    cup: 'Lightning Cup',
    trackName: 'Wii Grumble Volcano',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 28,
    cup: 'Lightning Cup',
    trackName: 'N64 Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 29,
    cup: 'Leaf Cup',
    trackName: 'DS Wario Stadium',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 30,
    cup: 'Leaf Cup',
    trackName: 'GCN Sherbert Land',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 31,
    cup: 'Leaf Cup',
    trackName: '3DS Music Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 32,
    cup: 'Leaf Cup',
    trackName: 'N64 Yoshi Valley',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 33,
    cup: 'Egg Cup',
    trackName: 'GCN Yoshi Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 34,
    cup: 'Egg Cup',
    trackName: 'Excitebike Arena',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 35,
    cup: 'Egg Cup',
    trackName: 'Dragon Driftway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 36,
    cup: 'Egg Cup',
    trackName: 'Mute City',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 37,
    cup: 'Triforce Cup',
    trackName: 'Wii Warios Gold Mine',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 38,
    cup: 'Triforce Cup',
    trackName: 'SNES Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 39,
    cup: 'Triforce Cup',
    trackName: 'Ice Ice Outpost',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 40,
    cup: 'Triforce Cup',
    trackName: 'Hyrule Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 41,
    cup: 'Crossing Cup',
    trackName: 'GCN Baby Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 42,
    cup: 'Crossing Cup',
    trackName: 'GBA Cheese Land',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 43,
    cup: 'Crossing Cup',
    trackName: 'Wild Woods',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 44,
    cup: 'Crossing Cup',
    trackName: 'Animal Crossing',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 45,
    cup: 'Bell Cup',
    trackName: '3DS Neo Bowser City',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 46,
    cup: 'Bell Cup',
    trackName: 'GBA Ribbon Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 47,
    cup: 'Bell Cup',
    trackName: 'Super Bell Subway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 48,
    cup: 'Bell Cup',
    trackName: 'Big Blue',
    isPlayed: false,
    isDLC: false,
  },
];
