export const data: {
  id: number;
  cup: string;
  trackName: string;
  isPlayed: boolean;
  isDLC: boolean;
}[] = [
  {
    id: 1,
    cup: 'Mushroom Cup',
    trackName: 'Mario Kart Stadium',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 2,
    cup: 'Mushroom Cup',
    trackName: 'Water Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 3,
    cup: 'Mushroom Cup',
    trackName: 'Sweet Sweet Canyon',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 4,
    cup: 'Mushroom Cup',
    trackName: 'Thwomp Ruins',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 5,
    cup: 'Flower Cup',
    trackName: 'Mario Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 6,
    cup: 'Flower Cup',
    trackName: 'Toad Harbor',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 7,
    cup: 'Flower Cup',
    trackName: 'Twisted Mansion',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 8,
    cup: 'Flower Cup',
    trackName: 'Shy Guy Falls',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 9,
    cup: 'Star Cup',
    trackName: 'Sunshine Airport',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 10,
    cup: 'Star Cup',
    trackName: 'Dolphin Shoals',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 11,
    cup: 'Star Cup',
    trackName: 'Electrodrome',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 12,
    cup: 'Star Cup',
    trackName: 'Mount Wario',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 13,
    cup: 'Special Cup',
    trackName: 'Cloudtop Cruise',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 14,
    cup: 'Special Cup',
    trackName: 'Bone Dry Dunes',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 15,
    cup: 'Special Cup',
    trackName: 'Bowsers Castle',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 16,
    cup: 'Special Cup',
    trackName: 'Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 17,
    cup: 'Shell Cup',
    trackName: 'Wii Moo Moo Meadows',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 18,
    cup: 'Shell Cup',
    trackName: 'GBA Mario Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 19,
    cup: 'Shell Cup',
    trackName: 'DS Cheep Cheep Beach',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 20,
    cup: 'Shell Cup',
    trackName: 'N64 Toads Turnpike',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 21,
    cup: 'Banana Cup',
    trackName: 'GCN Dry Dry Desert',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 22,
    cup: 'Banana Cup',
    trackName: 'SNES Donut Plains 3',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 23,
    cup: 'Banana Cup',
    trackName: 'N64 Royal Raceway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 24,
    cup: 'Banana Cup',
    trackName: '3DS DK Jungle',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 25,
    cup: 'Lightning Cup',
    trackName: 'DS Tick Tock Clock',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 26,
    cup: 'Lightning Cup',
    trackName: '3DS Piranha Plant Slide',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 27,
    cup: 'Lightning Cup',
    trackName: 'Wii Grumble Volcano',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 28,
    cup: 'Lightning Cup',
    trackName: 'N64 Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 29,
    cup: 'Leaf Cup',
    trackName: 'DS Wario Stadium',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 30,
    cup: 'Leaf Cup',
    trackName: 'GCN Sherbert Land',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 31,
    cup: 'Leaf Cup',
    trackName: '3DS Music Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 32,
    cup: 'Leaf Cup',
    trackName: 'N64 Yoshi Valley',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 33,
    cup: 'Egg Cup',
    trackName: 'GCN Yoshi Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 34,
    cup: 'Egg Cup',
    trackName: 'Excitebike Arena',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 35,
    cup: 'Egg Cup',
    trackName: 'Dragon Driftway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 36,
    cup: 'Egg Cup',
    trackName: 'Mute City',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 37,
    cup: 'Triforce Cup',
    trackName: 'Wii Warios Gold Mine',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 38,
    cup: 'Triforce Cup',
    trackName: 'SNES Rainbow Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 39,
    cup: 'Triforce Cup',
    trackName: 'Ice Ice Outpost',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 40,
    cup: 'Triforce Cup',
    trackName: 'Hyrule Circuit',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 41,
    cup: 'Crossing Cup',
    trackName: 'GCN Baby Park',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 42,
    cup: 'Crossing Cup',
    trackName: 'GBA Cheese Land',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 43,
    cup: 'Crossing Cup',
    trackName: 'Wild Woods',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 44,
    cup: 'Crossing Cup',
    trackName: 'Animal Crossing',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 45,
    cup: 'Bell Cup',
    trackName: '3DS Neo Bowser City',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 46,
    cup: 'Bell Cup',
    trackName: 'GBA Ribbon Road',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 47,
    cup: 'Bell Cup',
    trackName: 'Super Bell Subway',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 48,
    cup: 'Bell Cup',
    trackName: 'Big Blue',
    isPlayed: false,
    isDLC: false,
  },
  {
    id: 49,
    cup: 'Golden Dash Cup',
    trackName: 'Tour Paris Promenade',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 50,
    cup: 'Golden Dash Cup',
    trackName: '3DS Toad Circuit',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 51,
    cup: 'Golden Dash Cup',
    trackName: 'N64 Choco Mountain',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 52,
    cup: 'Golden Dash Cup',
    trackName: 'Wii Coconut Mall',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 53,
    cup: 'Lucky Cat Cup',
    trackName: 'Tour Tokyo Blur',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 54,
    cup: 'Lucky Cat Cup',
    trackName: 'DS Shroom Ridge',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 55,
    cup: 'Lucky Cat Cup',
    trackName: 'GBA Sky Garden',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 56,
    cup: 'Lucky Cat Cup',
    trackName: 'Ninja Hideaway',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 57,
    cup: 'Turnip Cup',
    trackName: 'Tour New York Minute',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 58,
    cup: 'Turnip Cup',
    trackName: 'SNES Mario Circuit 3',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 59,
    cup: 'Turnip Cup',
    trackName: 'N64 Kallmari Desert',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 60,
    cup: 'Turnip Cup',
    trackName: 'DS Waluigi Pinball',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 61,
    cup: 'Propeller Cup',
    trackName: 'Tour Sydney Sprint',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 62,
    cup: 'Propeller Cup',
    trackName: 'GBA Snow Land',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 63,
    cup: 'Propeller Cup',
    trackName: 'Wii Mushroom Gorge',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 64,
    cup: 'Propeller Cup',
    trackName: 'Sky-High Sundae',
    isPlayed: false,
    isDLC: true,
  },

  {
    id: 69,
    cup: 'Rock Cup',
    trackName: 'Tour London Loop',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 70,
    cup: 'Rock Cup',
    trackName: 'GBA Boo Lake',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 71,
    cup: 'Rock Cup',
    trackName: '3DS Rock Rock Mountain',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 72,
    cup: 'Rock Cup',
    trackName: 'Wii Maple Treeway',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 73,
    cup: 'Moon Cup',
    trackName: 'Tour Berlin Byways',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 74,
    cup: 'Moon Cup',
    trackName: 'DS Peach Gardens',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 75,
    cup: 'Moon Cup',
    trackName: 'Merry Mountain',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 76,
    cup: 'Moon Cup',
    trackName: '3DS Rainbow Road',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 77,
    cup: 'Fruit Cup',
    trackName: 'Tour Amsterdam Drift',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 78,
    cup: 'Fruit Cup',
    trackName: 'GBA Riverside Park',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 79,
    cup: 'Fruit Cup',
    trackName: 'Wii DK Summit',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 80,
    cup: 'Fruit Cup',
    trackName: 'Yoshis Island',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 81,
    cup: 'Boomerang Cup',
    trackName: 'Tour Bangkok Rush',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 82,
    cup: 'Boomerang Cup',
    trackName: 'DS Mario Circuit',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 83,
    cup: 'Boomerang Cup',
    trackName: 'GCN Waluigi Stadium',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 84,
    cup: 'Boomerang Cup',
    trackName: 'Tour Singapore Speedway',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 85,
    cup: 'Feather Cup',
    trackName: 'Tour Athens Dash',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 86,
    cup: 'Feather Cup',
    trackName: 'GCN Daisy Cruiser',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 87,
    cup: 'Feather Cup',
    trackName: 'Wii Moonview Highway',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 88,
    cup: 'Feather Cup',
    trackName: 'Squeaky Clean Sprint',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 89,
    cup: 'Cherry Cup',
    trackName: 'Tour Los Angeles Laps',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 90,
    cup: 'Cherry Cup',
    trackName: 'GBA Sunset Wilds',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 91,
    cup: 'Cherry Cup',
    trackName: 'Wii Koopa Cape',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 92,
    cup: 'Cherry Cup',
    trackName: 'Tour Vancouver Velocity',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 93,
    cup: 'Acorn Cup',
    trackName: 'Tour Rome Avanti',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 94,
    cup: 'Acorn Cup',
    trackName: 'GCN DK Mountain',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 95,
    cup: 'Acorn Cup',
    trackName: 'Wii Daisy Circuit',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 96,
    cup: 'Acorn Cup',
    trackName: 'Piranha Plant Cove',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 97,
    cup: 'Spiny Cup',
    trackName: 'Tour Madrid Drive',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 98,
    cup: 'Spiny Cup',
    trackName: '3DS Rosalinas Ice World',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 99,
    cup: 'Spiny Cup',
    trackName: 'SNES Bowser Castle 3',
    isPlayed: false,
    isDLC: true,
  },
  {
    id: 100,
    cup: 'Spiny Cup',
    trackName: 'Wii Rainbow Road',
    isPlayed: false,
    isDLC: true,
  },
];
